# Sidebar navigation

- label: '简介'
  link: '/'
- label: '开始'
  link: '/getting-started'
- label: 组件清单
  items:
    - label: 'AnnotationOperation'
      link: '/components/annotationOperation'
- label: 主题
  items:
    - label: 如何定制主题？
      link: /theming/how-to
- label: 配置补充说明
  items:
    - label: 所有类型
      link: /types/all

- label: 更多
  items:
    - label: FAQ
      link: /faq
    - label: 'Gitlab'
      link: https://gitlab.shlab.tech/wuhui/lb-smart
