exclude: >
  docs|
  node_modules|
  .git|
  .tox|migrations
fail_fast: true

repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
#      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: detect-private-key
        exclude: .gitlab/ci/ssh_key
      - id: mixed-line-ending
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-pytz
          - types-PyMySQL
          - types-requests
          - types-aiofiles
        args:  [--ignore-missing-imports]
